server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/
  instance:
    instance-id: order90
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10   # \u5BA2\u6237\u7AEF\u5411\u670D\u52A1\u7AEF\u53D1\u9001\u5FC3\u8DF3\u7684\u65F6\u95F4\u95F4\u9694\uFF0C\u9ED8\u8BA430\u79D2
    lease-expiration-duration-in-seconds: 10    # \u670D\u52A1\u7AEF\u5728\u6536\u5230\u6700\u540E\u4E00\u6B21\u5FC3\u8DF3\u540E\u7B49\u5F85\u65F6\u95F4\u4E0A\u9650\uFF0C \u9ED8\u8BA490\u79D2\uFF0C \u8D85\u65F6\u5C06\u5254\u9664\u670D\u52A1
