server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka1:7001/eureka/,http://eureka2:7002/eureka/
  instance:
    instance-id: order90
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10   # 客户端向服务端发送心跳的时间间隔，默认30秒
    lease-expiration-duration-in-seconds: 10    # 服务端在收到最后一次心跳后等待时间上限， 默认90秒， 超时将剔除服务
