server:
  port: 7001

eureka:
  instance:
    hostname: eureka1
    prefer-ip-address: true
  client:
    register-with-eureka: false # 是否向注册中心注册自己
    fetch-registry: false     #  只是注册中心 不需要检索服务  所以 false
    service-url:
      defaultZone: http://eureka2:7002/eureka/
  server:
    enable-self-preservation: false    #关闭自我保护机制
    eviction-interval-timer-in-ms: 10000    # 发送心跳时间
