server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
            #开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          enabled: true
      routes:
        # 路由的id,没有规定规则但要求唯一,建议配合服务名
        - id: payment_route
          #匹配后提供服务的路由地址
          #uri: http://localhost:8001
          uri: lb://CLOUD-PAYMENT-SERVICE   #lb，表示启用Gateway的负载均衡功能
          predicates:
            # 断言，路径相匹配的进行路由
            - Path=/payment/get/**
            #-After=2020-08-03T15:45:34.102+08:00[Asia/Shanghai]
            #- Before=2017-01-20T17:42:47.789-07:00[America/Denver]
            #- Cookie=username,zzyy
            #- Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数
            #- Host=**.atguigu.com
            #- Method=GET
            #- Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka1:7001/eureka/
  instance:
    instance-id: gateway9527
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10   # 客户端向服务端发送心跳的时间间隔，默认30秒
    lease-expiration-duration-in-seconds: 10    # 服务端在收到最后一次心跳后等待时间上限， 默认90秒， 超时将剔除服务